djangoFirstBlood/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^faktury/', include('invoices.urls')),)

invoices/urls.py
from django.conf.urls import patterns, url
from invoices import views

# urlpatterns = patterns('', url(r'^$', views.index, name='index'),)
urlpatterns = patterns('',
                       url(r'^$', views.login, name='login'),
#                      url(r'^$', views.index, name='index'),
                       url(r'^(?P<department_id>\d+)/$',
                           views.detail, name='detail'),
                       url(r'^(?P<input_d>\d+)/results/$',
                           views.results, name='results'),
                       url(r'^login/$',
                           views.login, name='login'),
                       url(r'^auth/$',
                           views.auth_view, name='authv'),
                       url(r'^logout/$',
                           views.logout, name='logout'),
#                      url(r'^loggedin/$',
#                          views.index, name='index'),
                      url(r'^loggedin/$',
                          views.loggedin, name='loggedin'),
                       url(r'^invalid/$',
                           views.invalid, name='invalid'),)

aua/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

invoices/models.py
from django.db import models


class Department(models.Model):
    """Name of department"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Agreement(models.Model):
    """Describe Agreement"""
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    department = models.ForeignKey(Department)
    description = models.CharField(max_length=100)
    total_gross = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    """Describe Invoice"""
    name = models.CharField(max_length=100)
    agreement = models.ForeignKey(Agreement)
    pay_date = models.DateField()
    gross = models.DecimalField(max_digits=11, decimal_places=2)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

aua/views.py
from django.shortcuts import render

# Create your views here.

invoices/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# from django.http import HttpResponseRedirect
# from invoices.models import *
from invoices.models import Invoice, Department, Agreement
from django.contrib import auth
from django.core.context_processors import csrf
from django.db.models import Sum


# def index(request):
#    list_department = Department.objects.all()
#    output = " ".join([p.name for p in list_department])

def index(request):
    list_department = Department.objects.all()
    context = {'list_department': list_department}
    return render(request, 'invoices/index.html', context)


def detail(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    return render(request, 'invoices/detail.html', {'department': department})


def results(request, input_d):
    response = "Results is %s"
    return HttpResponse(response % input_d)


def login(request):
    c = {}
    c.update(csrf(request))
    return render(request, 'invoices/login.html', c)


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    tup = (username, password)
    print(" ".join(tup))
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return redirect('loggedin')
#       return HttpResponseRedirect('/faktury/accounts/loggedin')
    else:
        return redirect('invalid')


def loggedin(request):
    depart_name = request.user.username
    list_invoi = Invoice.objects.filter(
        agreement__department__name=depart_name).order_by('agreement__name')
    maps = dict()
    for ele in Agreement.objects.annotate(suma=Sum('invoice__gross')).filter(
            department__name=depart_name).order_by('name'):
        maps[ele] = Invoice.objects.filter(agreement=ele)
    dic = {'full_name': request.user.username,
           'list_invoi': list_invoi, 'maps': maps}
    return render(request, 'invoices/loggedin.html', dic)


def logout(request):
    dic = {'full_name': request.user.username}
    auth.logout(request)
    return render(request, 'invoices/logout.html', dic)


def invalid(request):
    return render(request, 'invoices/invalid.html')

invoices/templates/invoices/detail.html
<h1>{{ department.name }}</h1>
<ul>
    {% for agreement in department.agreement_set.all %}
        <li>{{ agreement.name }}</li>
            {% for invoices in agreement.invoice_set.all %}
                <p>{{ invoices.name }}</p>
            {% endfor %}
    {% endfor %}
</ul>

invoices/templates/invoices/index.html
{% if list_department %}
    <ul>
        {% for name_dep in list_department %}
        <li><a href="{% url 'detail' name_dep.id %}">{{ name_dep.name }}</a>
        {% endfor %}
    </ul>
{% else %}
    <p>No department<p>
{% endif %}

invoices/templates/invoices/invalid.html
<h4>hello Mr. Improper (login;)! </h4>
<p> Click <a href="{% url 'login' %}">here</a> to start  process login again! </p>

invoices/templates/invoices/loggedin.html
<h4> Hello {{ full_name }} - jestes zalogowany! </h4>

{% if maps %}
    <ul>
        {% for key, val in maps.items %}
        <h5>Umowa: {{ key }}</h5>
            {% for valtmp in val %}
            <li>--->faktura {{ valtmp.name }}, wartość
                    {{ valtmp.gross }} </li>
            {% endfor %}
            ======>Suma  {{ key.suma }}
        {% endfor %}
    </ul>
{% endif %}

<p> Click <a href="{% url 'logout' %}"> tutaj</a> do wylogowania</p>

invoices/templates/invoices/login.html
{% if form.errors %}
    <p>Sorry</p>
{% endif %}

<form action="{% url 'authv' %}" method="post">{% csrf_token %}
    <label for="username">User name: </label>
    <input type="text" name="username" value="" id="username">
    <label for="password">Password: </label>
    <input type="password" name="password" value="" id="password"</label>
    <p/>
    <input type="submit" value="login" />
</form>

invoices/templates/invoices/logout.html
<h2> Aaah {{ full_name }} you are logout ! </h2>
<p> Click <a href="{% url 'login' %}">here</a> to login </p>
<!-- <p> Click <a href="/faktury/accounts/login/">here</a>to login</p> -->